import { Routes } from '@angular/router';
import { Dashboard } from './dashboard/dashboard';
import { ChartOfAccountsComponent } from './pages/chart-of-accounts/chart-of-accounts';
import { FinancialSettingsComponent } from './pages/financial-settings/financial-settings';
import { CashBoxesComponent } from './pages/cash-boxes/cash-boxes';
import { BanksComponent } from './pages/banks/banks';
import { PaymentVoucherComponent } from './pages/payment-voucher/payment-voucher';
import { ReceiptVoucherComponent } from './pages/receipt-voucher/receipt-voucher';
import { TrialBalanceComponent } from './pages/trial-balance/trial-balance';
import { WarehousesComponent } from './pages/warehouses/warehouses';
import { ItemsComponent } from './pages/items/items';
import { WarehouseGroupsComponent } from './pages/warehouse-groups/warehouse-groups';
import { StockInComponent } from './pages/stock-in/stock-in';
import { StockOutComponent } from './pages/stock-out/stock-out';
import { SupplierGroupsComponent } from './pages/supplier-groups/supplier-groups';
import { SuppliersComponentNew } from './pages/suppliers/suppliers';
import { IncomeStatementComponent } from './pages/reports/income-statement/income-statement';
import { BalanceSheetComponent } from './pages/reports/balance-sheet/balance-sheet';
import { CashFlowComponent } from './pages/reports/cash-flow/cash-flow';
import { RecurringTransactionsComponent } from './pages/reports/recurring-transactions/recurring-transactions';

export const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
  { path: 'dashboard', component: Dashboard },
  { path: 'financial', component: Dashboard },
  { path: 'financial/settings', component: FinancialSettingsComponent },
  { path: 'financial/chart-of-accounts', component: ChartOfAccountsComponent },
  { path: 'financial/cash-boxes', component: CashBoxesComponent },
  { path: 'financial/banks', component: BanksComponent },
  { path: 'financial/payment-voucher', component: PaymentVoucherComponent },
  { path: 'financial/receipt-voucher', component: ReceiptVoucherComponent },
  { path: 'financial/trial-balance', component: TrialBalanceComponent },
  { path: 'reports/income-statement', component: IncomeStatementComponent },
  { path: 'reports/balance-sheet', component: BalanceSheetComponent },
  { path: 'reports/cash-flow', component: CashFlowComponent },
  { path: 'reports/recurring-transactions', component: RecurringTransactionsComponent },
  { path: 'inventory', component: Dashboard },
  { path: 'inventory/warehouse-groups', component: WarehouseGroupsComponent },
  { path: 'inventory/warehouses', component: WarehousesComponent },
  { path: 'inventory/items', component: ItemsComponent },
  { path: 'inventory/stock-in', component: StockInComponent },
  { path: 'inventory/stock-out', component: StockOutComponent },
  { path: 'purchases', component: Dashboard },
  { path: 'purchases/supplier-groups', component: SupplierGroupsComponent },
  { path: 'purchases/suppliers', component: SuppliersComponentNew },
];
